[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
aptPkgs = ["chromium", "chromium-driver", "fonts-liberation", "libatk-bridge2.0-0", "libdrm2", "libxkbcommon0", "libxss1", "libasound2"]
